"use client";

import { motion } from "framer-motion";
import {
  FileText,
  ShieldAlert,
  Clock,
  Grid3X3,
  TrendingUp,
  Lightbulb,
  Download,
  Share2,
  CheckCircle2,
  AlertTriangle,
  XCircle,
} from "lucide-react";
import { AppLayout } from "@/components/AppLayout";
import { GlassCard } from "@/components/GlassCard";
import { GradientButton } from "@/components/GradientButton";
import { SectionHeader } from "@/components/SectionHeader";
import { CyberBadge } from "@/components/CyberBadge";
import { ReportCard } from "@/components/features/report/ReportCard";

const FADE_UP = (delay = 0) => ({
  initial: { opacity: 0, y: 16 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5, delay, ease: "easeOut" as const },
});

const ATTACK_TIMELINE = [
  { time: "02:17:44", event: "Initial Access via spear-phishing email", severity: "high" },
  { time: "02:19:01", event: "C2 beacon established to 185.220.xx.xx", severity: "critical" },
  { time: "02:21:33", event: "Process injection into lsass.exe", severity: "critical" },
  { time: "02:22:10", event: "Registry persistence key created", severity: "high" },
  { time: "02:24:58", event: "Ransomware payload deployed — 847 files encrypted", severity: "critical" },
];

const MITRE_MAPPINGS = [
  { id: "T1566.001", name: "Spear-phishing Attachment", tactic: "Initial Access" },
  { id: "T1059.001", name: "PowerShell Execution", tactic: "Execution" },
  { id: "T1547.001", name: "Registry Run Keys", tactic: "Persistence" },
  { id: "T1055.001", name: "DLL Injection", tactic: "Defense Evasion" },
  { id: "T1071.001", name: "Web Protocols C2", tactic: "Command & Control" },
  { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact" },
];

const RECOMMENDATIONS = [
  { status: "critical", text: "Patch email gateway to block macro-enabled attachments" },
  { status: "high", text: "Enable Credential Guard to prevent lsass memory access" },
  { status: "high", text: "Deploy EDR solution across all workstations" },
  { status: "medium", text: "Implement network segmentation to limit lateral movement" },
  { status: "medium", text: "Enable PowerShell script block logging (Event ID 4104)" },
  { status: "low", text: "Conduct quarterly phishing simulation training" },
];

const severityIcon = (s: string) => {
  if (s === "critical") return <XCircle className="w-3.5 h-3.5 text-red-400" />;
  if (s === "high") return <AlertTriangle className="w-3.5 h-3.5 text-orange-400" />;
  if (s === "medium") return <AlertTriangle className="w-3.5 h-3.5 text-yellow-400" />;
  return <CheckCircle2 className="w-3.5 h-3.5 text-blue-400" />;
};

export default function ReportPage() {
  return (
    <AppLayout>
      <div className="min-h-screen px-6 py-12 max-w-7xl mx-auto">
        {/* Header */}
        <motion.div {...FADE_UP(0)} className="flex items-start justify-between mb-10 flex-wrap gap-4">
          <div>
            <SectionHeader
              label="Incident Report"
              title="Operation ShadowLock"
              description="DFIR Investigation Report · Generated by TraceForge AI"
              align="left"
            />
          </div>

          <div className="flex items-center gap-2 mt-2">
            <GradientButton variant="secondary" size="sm">
              <Share2 className="w-3.5 h-3.5" />
              Share
            </GradientButton>
            <GradientButton size="sm">
              <Download className="w-3.5 h-3.5" />
              Export PDF
            </GradientButton>
          </div>
        </motion.div>

        {/* Report meta bar */}
        <motion.div {...FADE_UP(0.05)}>
          <GlassCard className="p-4 mb-8 flex flex-wrap gap-6 items-center">
            {[
              { label: "Case ID", value: "TF-2024-0314-001", mono: true },
              { label: "Scenario", value: "Operation ShadowLock", mono: false },
              { label: "Analyst", value: "PWNDORA Participant", mono: false },
              { label: "Date", value: "March 14, 2024 · 03:47 UTC", mono: true },
              { label: "Status", value: "Completed", badge: "green" as const },
            ].map((item) => (
              <div key={item.label}>
                <p className="text-[10px] text-white/30 font-mono uppercase tracking-widest mb-1">
                  {item.label}
                </p>
                {"badge" in item && item.badge ? (
                  <CyberBadge label={item.value} variant={item.badge} />
                ) : (
                  <p className={`text-sm text-white/80 ${item.mono ? "font-mono" : "font-medium"}`}>
                    {item.value}
                  </p>
                )}
              </div>
            ))}
          </GlassCard>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left column — wide */}
          <div className="lg:col-span-2 flex flex-col gap-6">
            {/* Executive Summary */}
            <motion.div {...FADE_UP(0.1)}>
              <ReportCard
                title="Executive Summary"
                icon={<FileText className="w-4 h-4" />}
                accentColor="text-blue-400"
              >
                <div className="space-y-3 text-sm text-white/50 leading-relaxed">
                  <p>
                    On March 14, 2024, a sophisticated ransomware campaign designated{" "}
                    <span className="text-white/70 font-medium">Operation ShadowLock</span>{" "}
                    was executed against corporate financial infrastructure. The threat
                    actor achieved initial access via a spear-phishing email targeting the
                    Finance department.
                  </p>
                  <p>
                    Within 7 minutes of initial compromise, the attacker established
                    command-and-control communication, performed credential harvesting via
                    LSASS injection, and deployed ransomware across 847 files on 3 file
                    servers. Total estimated data impact: <span className="text-red-400 font-mono">14.3 GB</span>.
                  </p>
                  <p className="text-white/30 text-xs font-mono border-t border-white/[0.05] pt-3">
                    Placeholder — full narrative generated by AI coach in Phase 2
                  </p>
                </div>
              </ReportCard>
            </motion.div>

            {/* Attack Timeline */}
            <motion.div {...FADE_UP(0.15)}>
              <ReportCard
                title="Attack Timeline"
                icon={<Clock className="w-4 h-4" />}
                accentColor="text-purple-400"
              >
                <div className="relative flex flex-col gap-0">
                  <div className="absolute left-3.5 top-0 bottom-0 w-px bg-white/[0.06]" />
                  {ATTACK_TIMELINE.map((ev, i) => (
                    <div key={i} className="relative flex items-start gap-4 pb-4 last:pb-0">
                      <div
                        className={`relative z-10 w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ml-2.5 ring-2 ring-black ${
                          ev.severity === "critical"
                            ? "bg-red-500"
                            : ev.severity === "high"
                            ? "bg-orange-500"
                            : "bg-yellow-500"
                        }`}
                      />
                      <div>
                        <span className="text-[10px] font-mono text-white/30">{ev.time}</span>
                        <p className="text-sm text-white/70 mt-0.5">{ev.event}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </ReportCard>
            </motion.div>

            {/* MITRE Mapping */}
            <motion.div {...FADE_UP(0.2)}>
              <ReportCard
                title="MITRE ATT&CK Mapping"
                icon={<Grid3X3 className="w-4 h-4" />}
                accentColor="text-purple-400"
              >
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {MITRE_MAPPINGS.map((m) => (
                    <div
                      key={m.id}
                      className="flex items-start gap-3 p-3 rounded-xl bg-white/[0.02] border border-white/[0.05]"
                    >
                      <span className="px-1.5 py-0.5 text-[9px] font-mono rounded bg-purple-500/15 text-purple-400 border border-purple-500/20 flex-shrink-0 mt-0.5">
                        {m.id}
                      </span>
                      <div>
                        <p className="text-xs font-medium text-white/70">{m.name}</p>
                        <p className="text-[10px] text-white/30 font-mono mt-0.5">{m.tactic}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </ReportCard>
            </motion.div>
          </div>

          {/* Right column */}
          <div className="flex flex-col gap-6">
            {/* Risk Score */}
            <motion.div {...FADE_UP(0.1)}>
              <ReportCard
                title="Risk Score"
                icon={<TrendingUp className="w-4 h-4" />}
                accentColor="text-red-400"
              >
                <div className="flex flex-col items-center py-4">
                  {/* Score ring */}
                  <div className="relative w-28 h-28 mb-4">
                    <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
                      <circle
                        cx="50" cy="50" r="42"
                        fill="none"
                        stroke="rgba(255,255,255,0.05)"
                        strokeWidth="10"
                      />
                      <circle
                        cx="50" cy="50" r="42"
                        fill="none"
                        stroke="url(#riskGrad)"
                        strokeWidth="10"
                        strokeLinecap="round"
                        strokeDasharray={`${2 * Math.PI * 42}`}
                        strokeDashoffset={`${2 * Math.PI * 42 * (1 - 0.87)}`}
                      />
                      <defs>
                        <linearGradient id="riskGrad" x1="0%" y1="0%" x2="100%" y2="0%">
                          <stop offset="0%" stopColor="#ef4444" />
                          <stop offset="100%" stopColor="#f97316" />
                        </linearGradient>
                      </defs>
                    </svg>
                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                      <span className="text-3xl font-bold text-white">87</span>
                      <span className="text-[10px] font-mono text-white/30">/ 100</span>
                    </div>
                  </div>
                  <CyberBadge label="CRITICAL" variant="red" />
                  <p className="text-xs text-white/30 text-center mt-3 font-mono">
                    Placeholder — scoring engine Phase 2
                  </p>
                </div>

                {/* Score breakdown */}
                <div className="space-y-2.5 border-t border-white/[0.05] pt-4">
                  {[
                    { label: "Impact", value: 95 },
                    { label: "Exploitability", value: 82 },
                    { label: "Scope", value: 78 },
                    { label: "Coverage", value: 91 },
                  ].map((s) => (
                    <div key={s.label}>
                      <div className="flex justify-between text-[11px] mb-1">
                        <span className="text-white/40 font-mono">{s.label}</span>
                        <span className="text-white/60 font-mono">{s.value}</span>
                      </div>
                      <div className="h-1.5 rounded-full bg-white/[0.05] overflow-hidden">
                        <div
                          className="h-full rounded-full bg-gradient-to-r from-red-500 to-orange-500"
                          style={{ width: `${s.value}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </ReportCard>
            </motion.div>

            {/* Recommendations */}
            <motion.div {...FADE_UP(0.15)}>
              <ReportCard
                title="Recommendations"
                icon={<Lightbulb className="w-4 h-4" />}
                accentColor="text-yellow-400"
              >
                <div className="flex flex-col gap-2.5">
                  {RECOMMENDATIONS.map((r, i) => (
                    <div
                      key={i}
                      className="flex items-start gap-2.5 p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]"
                    >
                      <span className="flex-shrink-0 mt-0.5">{severityIcon(r.status)}</span>
                      <p className="text-xs text-white/60 leading-relaxed">{r.text}</p>
                    </div>
                  ))}
                </div>

                <p className="text-[10px] text-white/20 text-center mt-4 font-mono">
                  AI-generated recommendations · Phase 2
                </p>
              </ReportCard>
            </motion.div>

            {/* Report actions */}
            <motion.div {...FADE_UP(0.2)}>
              <GlassCard className="p-5 flex flex-col gap-3">
                <p className="text-xs font-semibold text-white/60 mb-1">Export Options</p>
                <GradientButton className="w-full justify-center" size="sm">
                  <Download className="w-3.5 h-3.5" />
                  Export as PDF
                </GradientButton>
                <GradientButton variant="secondary" className="w-full justify-center" size="sm">
                  <Share2 className="w-3.5 h-3.5" />
                  Share Report
                </GradientButton>
                <p className="text-[10px] text-white/20 text-center font-mono">
                  Export functionality · Phase 2
                </p>
              </GlassCard>
            </motion.div>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
